### ISSUE TITLE
Incorrect percentages

### ISSUE THREAD

**Issue by casey** [hsjoberg/fork-explorer#15]
I think the signalling/ucoming/non-signalling percentages are calculated incorrectly.

This screenshot shows the page, as well as a calculator showing the expected values:

<img width="1325" alt="Screen Shot 2021-05-01 at 8 45 06 PM" src="https://user-images.githubusercontent.com/1945/116801383-5581a500-aabe-11eb-9fae-70525c34744d.png">

PS Love this project!

**Comment by hsjoberg** [comment]
@casey Thank you for reporting about this.
Yes, it looks like a regression was recently introduced, I'll address this and deploy an update soon.

> PS Love this project!

I appreciate that! 🙏

**Comment by hMsats** [comment]
Also why equal?


Foundry USA | 6.02% | ✅
-- | -- | --
Huobi.pool | 6.02% |  


SlushPool | 3.61% | ✅
-- | -- | --
1THash | 3.61% | 🚫


ArkPool | 1.20% | 🚫
-- | -- | --
BTC.TOP | 1.20%


SBI Crypto | 0.60% | 🚫
-- | -- | --
EMCDPool | 0.60% | 🚫
SpiderPool | 0.60% |

**Comment by hsjoberg** [comment]
@hMsats Most likely because there aren't that many blocks mined yet for this period. I don't think there's any errors here.

**Comment by hMsats** [comment]
@hsjoberg Yeah, that could be it. Just wanted it to get your attention just in case. Nice website!

**Comment by hsjoberg** [comment]
@hMsats Thanks for caring and reporting. Cheers! 🙂
