### ISSUE TITLE
Mode for colorblind people

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/fork-explorer#2]

**Comment by hsjoberg** [comment]
One solution for colorblind mode is to make everything black and white, and then have "T/F" markings for the blocks

**Comment by mutatrum** [comment]
Take a look at what I did at https://hodl.camp/, there is a low-vision icon on the top that toggles between different palettes. The palettes come from https://colorbrewer2.org/, which are built in into chroma-js.
