### ISSUE TITLE
Change `miners` to `mining pools`

### ISSUE THREAD

**Issue by prayank23** [hsjoberg/fork-explorer#22]
Can we change `miners` to `mining pools`?

https://github.com/hsjoberg/fork-explorer/blob/e664a74606b865f981927729a885e4082fedbca7/frontend/components/SiteMenu.tsx#L36

https://github.com/hsjoberg/fork-explorer/blob/13af28132ef1e2da252df09d756f05397d81f532/frontend/pages/miners.tsx#L82

This website is now used by lot of people and many newbies may assume there is no difference between _miners_ and _mining pools_.

**Comment by hsjoberg** [comment]
Thank you for the opening this issue @prayank23.
I agree, let's have this changed! My intention was of course not to confuse users and this is an important distinction to understand.

**Comment by hsjoberg** [comment]
@prayank23 This was addressed in a39d1e3 and has been deployed to production!
