### ISSUE TITLE
/miners Show potential total share of activated Mining pools

### ISSUE THREAD

**Issue by bauslo** [hsjoberg/fork-explorer#27]
On the Mining Pools overview page https://taproot.watch/miners please show at the top (or bottom) the total share of Taproot activated Mining pools.

Meaning: Currently there are 4 mining pools which have Taproot activated:
1. F2Pool
2. Poolin
3. Foundry USA
4. SlushPool
Add those shares together and we'd get roughly **35.55%** of Taproot activated Hashrate.

thx

**Comment by hsjoberg** [comment]
Thank you for the suggestion @bauslo!
This was fixed in 5665a68.
