### ISSUE TITLE
Reducing "Unrecognized miners"

### ISSUE THREAD

**Issue by 0xB10C** [hsjoberg/fork-explorer#36]
I've been maintaining a [fork]([0xB10C/known-mining-pools](https://github.com/0xB10C/known-mining-pools)) of [btccom/Blockchain-Known-Pools](https://github.com/btccom/Blockchain-Known-Pools) with the goal of better coverage and higher accuracy. This should help you detect e.g. blocks by WAYI.CN (https://github.com/0xB10C/known-mining-pools/pull/31) which currently appear as "Unrecognized miners" on taproot.watch.

However, I'm not sure if you can 'retry' pool identification on your end.

**Comment by hsjoberg** [comment]
Thank you for bringing this up @0xB10C.

> However, I'm not sure if you can 'retry' pool identification on your end.

Oh this is very easy, I save everything in a Typescript file: https://github.com/hsjoberg/fork-explorer/blob/master/backend/blocks/miners.ts
Everything is saved in memory, so I'm bootstrapping all blocks on startup.

I'll change to your version instead.

**Comment by hsjoberg** [comment]
Fixed in cac5e4499fe1ae88e24b19bec65f87b8ae7df17c.
