### ISSUE TITLE
Theming support

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/fork-explorer#40]
In preparation for colorblindness mode, styled-components theming support is needed.

**Comment by mutatrum** [comment]
Take a look at what I did at https://hodl.camp/, there is a low-vision icon on the top that toggles between different palettes. The palettes come from https://colorbrewer2.org/, which are built in into chroma-js.

**Comment by hsjoberg** [comment]
Implemented in ff993eab807e7f121a9cfca12fa271281e05a780
