### ISSUE TITLE
Correct Taproot activation threshold?

### ISSUE THREAD

**Issue by schildbach** [hsjoberg/fork-explorer#51]
I may be understanding this wrong, but the activation threshold for Taproot on mainnet is 1815 blocks, according to BIP341. 

https://github.com/hsjoberg/fork-explorer/blob/41ddfe5c72e1c9fd4fa099e5aa5b9970b1fe6a49/config/config.ts_TEMPLATE#L105

**Comment by hsjoberg** [comment]
Oh this is definitely wrong. The production site (https://taproot.watch) got it right but I probably forgot to change it in the template as well. Good find, thank you!

**Comment by hsjoberg** [comment]
Fixed in 7516225
