### ISSUE TITLE
Green favicon is misleading

### ISSUE THREAD

**Issue by ysangkok** [hsjoberg/fork-explorer#55]
The green favicon could be interpreted as a summary of taproot.watch, which would make the user think Taproot will definitely be activated, because the icon is green. But that wouldn't be true, since the website says "Taproot cannot be locked in within this period", but the favicon is green. I propose the favicon have a question mark if it could still go either way.

**Comment by fiatjaf** [comment]
The favicon could change to reflect the status of the latest block instead of a static green.

**Comment by ysangkok** [comment]
Given that block times are somewhat unpredictable, I think there is no use in that, since if a user isn't looking at the full page, there is no reason to assume that they are interested in information about every single block. Without a counter, you wouldn't know if a new block has been mined that has the same colour as the previous, or if no block was mined.

**Comment by Giszmo** [comment]
The green favicon is iconic (pun intended) of the taproot activation by speedy trial by now. Please close this issue. It's pure noise.

**Comment by hsjoberg** [comment]
Sorry for the late response @ysangkok.
I agree with @Giszmo, the green square is more of a meme at this point.
I don't believe that the favicon should be used as a status indicator of any kind, it's better to just go to the actual site then.
