### ISSUE TITLE
Mention that 'signalling' is not voting

### ISSUE THREAD

**Issue by prayank23** [hsjoberg/fork-explorer#57]
```HTML
Green block means that it signalled 'readiness' for Taproot activation, red block means that it did not. Transparent blocks are upcoming blocks within this period. <a href="https://bitcoin.stackexchange.com/questions/97043/is-there-an-active-list-of-bips-currently-open-for-voting/"> Signalling is NOT voting</a>
```

Lot of users consider miners signalling as voting which is not true I have shared a link of an [answer by Pieter Wuille](https://bitcoin.stackexchange.com/questions/97043/is-there-an-active-list-of-bips-currently-open-for-voting/) and there are lot of other posts by different Bitcoin devs to clarify the same thing. Hope you can add this and people do not consider it as voting.

![image](https://user-images.githubusercontent.com/13405205/118011950-301e5200-b36e-11eb-9eae-705a147b56a6.png)

**Comment by hsjoberg** [comment]
I like this. That's for opening the issue @prayank23.

**Comment by hsjoberg** [comment]
Partly addressed now. The paragraphs does not support hyperlinks atm.
