### ISSUE TITLE
Add a script to generate previous epochs

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/fork-explorer#58]
Some external tools are basing their data on the `/blocks` API call.
The application right now only saves the current difficulty period so we might want to provide a way to generate previous ones (perhaps even use it in this project (`/?epoch=X`)).

**Comment by AndrewLaganaro** [comment]
I was just thinking about that, I need to see the last epoch to get its data but there's no option to that on the website ): Support this!

**Comment by AndrewLaganaro** [comment]
Any news on that one?

**Comment by hsjoberg** [comment]
@AndrewLaganaro Yes! I've implemented a script to [generate periods](https://github.com/hsjoberg/fork-explorer#generating-block-data-from-a-specific-difficulty-period).

The three periods of the Taproot Speedy Trial softfork are available here:

https://taproot.watch/blocks/338
https://taproot.watch/blocks/339
https://taproot.watch/blocks/340

I'll have the actual webpages restored eventually, but at least the data is available now.

**Comment by AndrewLaganaro** [comment]
ohhh huge thanks man! I really appreciate that as I'm going to use that data on a data analysis project of mine!

**Comment by hsjoberg** [comment]
@AndrewLaganaro Sounds great! 🚀 

Closing this issue.
Implemented in b77db80076b7fd35496d9a05359a7b6c73414bc7 and 95ef039dc8c3be6b66fae935e4ced617cad08ae8.

**Comment by hsjoberg** [comment]
@AndrewLaganaro FYI I moved the API call from /blocks/[period] to /period/[period]. So the URLs are:

https://taproot.watch/period/338
https://taproot.watch/period/339
https://taproot.watch/period/340
