### ISSUE TITLE
Enable HSTS policy on taproot.watch

### ISSUE THREAD

**Issue by hsjoberg** [hsjoberg/fork-explorer#59]
We will never serve content on HTTP, so to improve security it makes sense to enable [HSTS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security).

Serving via HTTPS is currently out of scope of fork-explorer, so this has to be done on a reverse proxy (Nginx, Apache, Caddy, etc). taproot.watch uses Caddy, so I'll take a look there.

**Comment by stp-ip** [comment]
This added to the site block for Caddy should do:
```
header {
	 Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
}
```
This sets the HSTS policy and also enables the site to be preloaded within browsers.
Preloading form, after the header is set: https://hstspreload.org/

**Comment by hsjoberg** [comment]
@stp-ip Thank you! This has now been enabled on taproot.watch and txt.taproot.watch. 💯
