### ISSUE TITLE
Count "potential percentage" as well as last percentage

### ISSUE THREAD

**Issue by copumpkin** [hsjoberg/fork-explorer#61]
We've observed that a lot of pools have staged rollouts, where they seem to flip-flop back and forth between signaling and non-signaling blocks. Largely I think we should think of those as "eventually signaling" and it would be nice to sum up the percentages of pools that have a nonzero signaling block number in the current period and show that sum. So for example, right now the sum shows 60.47%, because BTC.com's latest block wasn't signaling, even though some of their blocks do signal. Same with Huobi Pool and 1THash, and probably others before the process is over. Those added up would add another 22.09% "eventual hashrate" to the total, taking us to 82.56%. Obviously the number should be qualified and explained, but it seems useful to report because it's likely that all these staged rollouts would be done within a couple of weeks.

**Comment by Giszmo** [comment]
If I was managing a pool hostile to Taproot, I would probably make taproot signalling opt-in for my miners. The lazy ones would not signal Taproot and those who want to signal Taproot and take action to do so would remain with my pool instead of leaving for another pool. Are we sure this isn't what's going on? Are BTC.com miners maybe mining for two different internal pools?

**Comment by copumpkin** [comment]
We can't really be sure of anything, but any large responsible well run operation will do staged deployments of changes (update one back-end pool server, make sure things look good for a while, and if so, update more), so the flip-flopping we're seeing from a lot of pools seems pretty understandable to me.

**Comment by hsjoberg** [comment]
I attempted to address this in #65, it's live on https://taproot.watch right now, but you can also try the Cloudflare Pages demo link as the text won't show up if the numbers match.

https://5cefb921.fork-explorer.pages.dev/miners

**Comment by copumpkin** [comment]
Awesome, thanks!
