### ISSUE TITLE
Show 144 block signaling average

### ISSUE THREAD

**Issue by MaxHillebrand** [hsjoberg/fork-explorer#66]
It would be nice to see what percentage of blocks out of the last X blocks that signal readiness. This would be a very up to date "real time" signaling rate.

**Comment by MaxHillebrand** [comment]
Corey Edwards wrote [a script for this](https://twitter.com/InPHARMaticist/status/1395734932475957250), @billygarrison added a argument for the number of blocks [here](https://github.com/billygarrison/bitcoin-scripts/blob/master/taproot-signalling.sh).

**Comment by hsjoberg** [comment]
I opened pull request #69 for a stats page, showing 144 block moving average.
Demo is available here: https://ma.fork-explorer.pages.dev

**Comment by MaxHillebrand** [comment]
Thank you for shipping this so swiftly!

**Comment by hsjoberg** [comment]
Cheers @MaxHillebrand!
