### ISSUE TITLE
Wrong forecast in txt version

### ISSUE THREAD

**Issue by rafaelpac** [hsjoberg/fork-explorer#76]
Wrong forecast in txt version "Taproot will not lock in with the current signalling ratio (100.00%)"
The regular version is ok.

![image](https://user-images.githubusercontent.com/6444444/120093067-14e16f80-c0ee-11eb-912d-88cc80a42963.png)

**Comment by hsjoberg** [comment]
Thank you for opening this issue @rafaelpac.
This has been fixed now.
